sampling:
  - layer: 1
    neighbor: 
      - 10
    strategy: 'recent'
    prop_time: False
    history: 1
    duration: 0
    num_thread: 8
    no_neg: True
memory: 
  - type: 'node'
    dim_time: 100
    deliver_to: 'neighbors'
    mail_combine: 'last'
    memory_update: 'transformer'
    attention_head: 2
    mailbox_size: 10
    combine_node_feature: False
    dim_out: 100
gnn:
  - arch: 'identity'
np:
  - r_dim: 256
    z_dim: 256
    h_dim: 256
    y_dim: 128
    t_dim: 256
    out_dim: 256
    l: 10
    r_tol: 1e-5
    a_tol: 1e-7
    method: "dopri5"
    context_split: 0.1
    old_as_context: true
train:
  - epoch: 999
    batch_size: 600
    test_batch_size: 100
    history_encoding_batch_size: 600
    lr: 0.00001
    dropout: 0.1
    train_neg_size: 1
    att_dropout: 0.1
    # all_on_gpu: True
    patience: 5
    train_ratio: 0
    test_split_num: 5